antora:
  extensions:
  - require: '@springio/antora-extensions'
    root_component_name: 'ldap'
site:
  title: Spring LDAP
  url: https://docs.spring.io/spring-ldap/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-ldap
    # Refname matching:
    # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
    branches: [main, '3.3.x', '{4..99}.*.x']
    tags: ['3.3.*','{4..99}.*']
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/include-code-extension'
    - '@springio/asciidoctor-extensions/javadoc-extension'
  attributes:
    page-related-doc-categories: security
    page-related-doc-projects: framework
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.25/ui-bundle.zip
    snapshot: true
