name: "002: Check For Releases"

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  planner:
    name: "Is there a release that is ready today?"
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.release-version.outputs.release-version }}
      should-release: ${{ steps.count-issues.outputs.issue-count > 0 }}
    steps:
      - uses: actions/checkout@v4
      - id: compute-version
        uses: jzheaux/spring-io-actions/compute-version@main
      - if: ${{ steps.compute-version.outputs.snapshot == 'true' }}
        id: release-version
        uses: jzheaux/spring-io-actions/get-todays-release-version@main
        with:
          snapshot-version: ${{ steps.compute-version.outputs.snapshot }}
          milestone-token: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ steps.release-version.outputs.release-version != '' }}
        id: count-issues
        uses: jzheaux/spring-io-actions/count-open-issues@main
        with:
          milestone: ${{ steps.release-version.outputs.release-version }}

  release-launcher:
    needs: planner
    if: ${{ needs.planner.outputs.should-release == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Push Release Version ${{ needs.planner.outputs.release-version }}"
        uses: jzheaux/spring-io-actions/push-release-version@main
        with:
          version: ${{ needs.planner.outputs.release-version }}
