permissions:
  issues: write
name: "003B: Schedule Milestones"
on:
  milestone:
    types: [ closed ]

jobs:
  schedule-milestones:
    name: Schedule Milestones
    runs-on: ubuntu-latest
    steps:
      - id: next-release-milestone
        name: "Compute Milestone After ${{ github.event.milestone.title }}"
        uses: jzheaux/spring-io-actions/compute-next-version@main
        with:
          version: ${{ github.event.milestone.title }}
          token: ${{ secrets.GITHUB_TOKEN }}
          website-token: ${{ secrets.WEBSITE_TOKEN }}
          website-repository: 'jzheaux/jzheaux-website-content'
      - name: "Ensure ${{ steps.next-release-milestone.outputs.next-version }} Scheduled"
        uses: jzheaux/spring-io-actions/schedule-milestone@main
        if: ${{ steps.next-release-milestone.outputs.release-type  == 'oss' }}
        with:
          version: ${{ steps.next-release-milestone.outputs.next-version }}
          version-date: ${{ steps.next-release-milestone.outputs.next-version-date }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: next-next-release-milestone
        name: "Compute Milestone After ${{ steps.next-release-milestone.outputs.next-version }}"
        uses: jzheaux/spring-io-actions/compute-next-version@main
        if: ${{ steps.next-release-milestone.outputs.next-version-type  == 'oss' }}
        with:
          version: ${{ steps.next-release-milestone.outputs.next-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          website-token: ${{ secrets.WEBSITE_TOKEN }}
          website-repository: 'jzheaux/jzheaux-website-content'
      - name: "Ensure ${{ steps.next-next-release-milestone.outputs.next-version-type }} Scheduled"
        uses: jzheaux/spring-io-actions/schedule-milestone@main
        if: ${{ steps.next-next-release-milestone.outputs.next-version-type  == 'oss' }}
        with:
          version: ${{ steps.next-next-release-milestone.outputs.next-version }}
          version-date: ${{ steps.next-next-release-milestone.outputs.next-version-date }}
          token: ${{ secrets.GITHUB_TOKEN }}